version: '3.1'
services:
  yacare:
    image: munirg/yacare:testing
    volumes:
      - ../yacare/:/root/yacare/
      - composer-cache:/root/.composer/cache/files
    tty: true
    depends_on:
      - db
    environment:
      - YACARE_SECRET=${YACARE_SECRET}
      - SYMFONY_ENV=test
  db:
    image: mariadb:10.2
    volumes:
      - ../yacare/tests/_data/db/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=yacatest
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=yacatest
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  composer-cache:
